name: Package Install Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  install-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        install-method:
          - "."
          - ".[plots]"
          - ".[alt-algos]"
          - ".[all]"

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ${{ matrix.install-method }}

      - name: Verify installation
        run: python -c "import reddwarf"
