name: "Run Tests"

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
    inputs:
      enableCache:
        description: "Enable cache of installed dependencies"
        type: boolean
        default: true

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # See: https://devguide.python.org/versions/
        # See: https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json
        python-version:
          - "3.10"
          - "3.13"
          # Numba (required by pacmap) is being ported to v3.14
          # See: https://github.com/numba/numba/issues/9957
          # - "3.14"
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          # For v3.14
          allow-prereleases: true

      - uses: astral-sh/setup-uv@v5
        with:
          # Enable cache, except when manually triggered and explicitly disabled.
          enable-cache: ${{ github.event_name != 'workflow_dispatch' || inputs.enableCache }}
          version: "latest"
          # As a library, we're not version-controlling uv.lock, so need pyproject.toml check.
          # See: https://github.com/astral-sh/setup-uv/issues/261#issue-2818259989
          cache-dependency-glob: |
            **/*(requirements|constraints)*.(txt|in)
            **/pyproject.toml
            **/uv.lock
          cache-suffix: python-${{ matrix.python-version }}

      - name: Create virtual environment
        run: make venv

      - name: Install dependencies
        run: make install-dev

      - name: Test with pytest
        run: make test

      - name: Test notebooks
        run: make test-nb
